name: Create a new Issue
on: [workflow_dispatch]
env:
  NAME: "srini"
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%Y/%m")"
          echo "::set-output name=context:: somecontext"

      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: "New Issue on ${{ steps.date.outputs.today }}"
          body: |
            ## This week's TODO
            Context Is , ${{ steps.date.outputs.context }}!
            Added by ${{ env.NAME }}
            - [ ] Have a meeting with UX team
            - [ ] Check the dashboard
            
          labels: |
            meeting
            weekly
      
