name: Dump Specific Env Info
on: [workflow_dispatch]
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print owner info
        env:
          GITHUB_OWNER: ${{ toJson(github.repository_owner) }}
        run: echo "$GITHUB_OWNER"
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
