name: Dump Specific Env Info
on: [workflow_dispatch]
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print owner info
        env:
          GITHUB_OWNER: ${{ toJson(github.repository_owner) }}
        run: echo "$GITHUB_OWNER"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
