name: Dump Specific Env Info
on: [workflow_dispatch]
jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Print owner info
        env:
          GITHUB_OWNER: ${{ toJson(github.repository_owner) }}
        run: echo "$GITHUB_OWNER"
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@v1
        with:
          number: 1
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.repository_owner }}!

