name: learn_outputs
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${ steps.step1.outputs.test1 }
      output2: ${ steps.step2.outputs.test2 }
    steps:
      - id: step1
        run: echo "test1=hello1" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test2=hello2" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      output1: ${ needs.job1.outputs.output1 }
      output2: ${ needs.job1.outputs.output2 }
    steps:
     - run: echo "$OUTPUT1"
     - run: echo "$OUTPUT1"
    
  
    
  
